INSERT INTO `products` (`id`, `name`, `code`, `category_id`, `image`, `description`, `price`, `created_at`,
                        `updated_at`)
VALUES (1, "iPhone 13 128GB", "iphone_13_128", 3, NULL, "Excellent advanced phone with 129 gb memory", 4499,
        NULL, NULL),
       (2, "iPhone 13 256GB", "iphone_13_256", 3, NULL, "Excellent advanced phone with 256 gb memory", 4999,
        NULL, NULL),
       (3, "Samsung Galaxy S22 8/128GB", "samsung_s22_128", 3, NULL, "Why pay for extra? The legendary Samsung Galaxy S22", 3999, NULL,
        NULL),
       (4, "Samsung Galaxy S22 Ultra 8/128GB", "samsung_s22_ultra_128", 3, NULL, "Great Classic Samsung", 5900, NULL, NULL),
       (5, "Headphones Philips Fidelio L3", "philips_fidelio_l3", 4, NULL, "Great sound from Philips", 1300, NULL, NULL),
       (6, "DJI Pocket 2 Creator Combo", "pocket_2", 4, NULL, "Capture your best moments with this camera", 2400, NULL,
        NULL),
       (7, "Camera Sony Cyber-shot DSC-RX10 III", "sony_cyber-shot", 4, NULL,
        "Serious video shooting requires a serious camera. Sony Cyber-shot DSC-RX10 III is the best choice for this purpose!", 6300,
        NULL, NULL),
       (8, "Coffee machine DeLongi", "delongi", 5, NULL, "A good morning starts with good coffee!", 3499, NULL,
        NULL),
       (9, "Fridge Samsung RB38T603CS9", "Samsung_RB38T603CS9", 5, NULL, "Great fridge for a big family!", 2999, NULL, NULL),
       (10, "Braun MultiQuick 7", "braun_multiquick", 5, NULL, "For the wildest ideas", 389, NULL, NULL),
       (11, "Meat grinder Bosch", "grinder_bosch", 5, NULL,
        "Love homemade meatballs? You should definitely check out this meat grinder!", 499, NULL, NULL);
